spring.application.name=Flashcard
spring.ai.openai.base-url =https://hackathon-1pvp.onrender.com/api/ai-model/v2/chat/
spring.ai.openai.api-key = sk_79570a7ab6c9eee78652a85bff9b2fdde8d64066
spring.ai.openai.chat.option.model=default